# -----------------------------------------------------------------
# HOUSE STATES
#  - Morning
#  - Daytime
#  - Dusk
#  - Evening
#  - Bedtime
#  - Night
#  - Nightpath (not automated here)
#------------------------------------------------------------------

#------------------------------------------------------------------
# Nighttime
# Fixed time, or by request
#------------------------------------------------------------------
- alias: house-state-night
  trigger:
    - at: "22:45"
      platform: time
  condition:
    # unless it's already in this state
    condition: template
    value_template: "{{ not is_state('input_select.house_state','Night') }}"
  action:
    - data:
        entity_id: input_select.house_state
        option: Night
      service: input_select.select_option
