# -------------------------------------------------------------------
# Occupancy Triggers and timings
# Sensors should have friendly name in the form:
#   <roomname> + <optional qualifier> + "Motion Sensor"
#     e.g. Bedroom Motion Sensor
#     e.g. Bedroom Hallway Motion Sensor
# Timers declared in config in the form:
#   <roomname>_motion_timer
#   e.g. bedroom_motion_timer
# -------------------------------------------------------------------
- alias: room-occupancy-trigger
  initial_state: true
  trigger:
    # occupancy motion sensors
    - entity_id:
      - binary_sensor.bathroom_motion_1_occupancy
      - binary_sensor.bedroom_motion_occupancy
      - binary_sensor.bedroom_hallway_motion_occupancy
      - binary_sensor.entryway_motion_occupancy
      - binary_sensor.kitchen_motion_occupancy
      - binary_sensor.livingroom_motion_occupancy
      platform: state
      to: "on"

  # If a room is occupied, it's occupied. It's a fact. It's not conditional.
  # How the system responds to the "occupancy events" is handled via triggers
  # listening to the state change in the occupancy flag (input_boolean)
  condition: []

  action:
    # # DEBUG -- Show me the values of the trigger.to_state
    # - service: persistent_notification.create
    #   data_template:
    #     title: >
    #       Occupancy Trigger {{ trigger.to_state.attributes.friendly_name.split(' ', 1)[0] }}
    #     message: |
    #       Trigger Platform Type: {{ trigger.platform }}
    #       Entity Name: {{ trigger.to_state.attributes.friendly_name}} {{'\n'-}}
    #       Triggering Entity ID: {{ trigger.entity_id }}
    #       Occupancy Timer: timer.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_motion_timer {{'\n'-}} 
    #       Occupancy Flag: input_boolean.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_motion_occupancy

    # Set occupancy duration timer
    #   bump up to default on EVERY motion detection
    #   In my case, motion sensors reset at about 2min
    #   Timers are set to 5 min for each room
    #   Timers need to be a bit longer than the sensor reset time to
    #   removes the "flicker" that can occur from "bouncing"
    #   ENHANCEMENT: add a time-of-day variable to the timer durations
    - service: timer.start
      data_template:
        entity_id: timer.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_motion_timer

    # # Set room occupancy flag
    # # Room behaviors are all triggerd on the room occupancy state change
    - service: input_boolean.turn_on
      data_template:
        entity_id: input_boolean.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_occupancy