# -------------------------------------------------------
# Input select
# -------------------------------------------------------
# Alarm Panel Modes
alarm_modes:
  name: "Alarm Modes"
  options:
    - Home
    - Away
    - Vacation
