# -------------------------------------------------------
# Input select
# -------------------------------------------------------
# House Automation Modes
house_auto_modes:
  name: House Auto Modes
  options:
    - "Auto"
    - "Entertaining"
    - "Manual"